### PR TITLE
add initial django project

### PR DESCRIPTION
**Pull request by jsatt**
has just enough to get started plus a sample model for protohealth data
associated with a boundary

### CODE REVIEW

**Comment by jsatt** [comment]
@jwhitlock, Here's what I got for a start. Any feedback on the direction before we merge this?

**Comment by jwhitlock** [comment]
It looks good to me.  Merge it.

How do we want to track dataset metadata?  Track the import time, applicable dates, source URLs as database tables?  Or will he have on-site metadata, like 'protohealth data from X study, Jan 2014'?  I think we decide later, add migrations as needed.

**Comment by jsatt** [comment]
I was kind of thinking about that too. Maybe we can get a few more of the sources we want to use for the demo and see what structure makes sense.

**Comment by groovecoder** [comment]
Re: tracking dataset metadata, we should use [DCAT](http://www.w3.org/TR/vocab-dcat/). It's a W3C recommendation, it is part of the [Government Linked Data Working Group](http://www.w3.org/2011/gld/wiki/Main_Page) and the [White House Project Open Data Common Core](http://project-open-data.github.io/schema/).

Downside: it's RDF. :/

**Pull request merged**
